#!/bin/bash


mkdir -vp ~/.config/fish/functions
cp -v config/fish/functions/*.fish ~/.config/fish/functions/
cp -v config/fish/config.fish ~/.config/fish/
echo appending bash aliases on config.fish
cat .bash_aliases >> ~/.config/fish/config.fish

echo installing helper funcitons to manage copy/paste
curl --silent "https://raw.githubusercontent.com/fish-shell/fish-shell/master/share/functions/fish_clipboard_copy.fish"  > ~/.config/fish/functions/fish_clipboard_copy.fish
curl --silent "https://raw.githubusercontent.com/fish-shell/fish-shell/master/share/functions/fish_clipboard_paste.fish"  > ~/.config/fish/functions/fish_clipboard_paste.fish

chmod +x ~/.config/fish/functions/*.fish

echo "ready to fish"
