return { }
-- {
-- 	"romainl/vim-qf", -- https://github.com/romainl/vim-qf"
-- 	config = function()
-- 		vim.keymap.set(
-- 			"n",
-- 			"<leader>tq",
-- 			"<Plug>(qf_qf_toggle)",
-- 			{ desc = "Toggle quickfix window", noremap = true }
-- 		)
-- 	end,
-- },
-- {
-- 	"windwp/nvim-ts-autotag", -- https://github.com/windwp/nvim-ts-autotag
-- 	config = function()
-- 		local cfg = {
-- 			enable_rename = true,
-- 			enable_close = true,
-- 			enable_close_on_slash = true,
-- 		}
-- 		require("nvim-ts-autotag").setup({
-- 			did_setup = true,
-- 			per_filetype = {
-- 				["html"] = cfg,
-- 				["xml"] = cfg,
-- 				["mdx"] = cfg,
-- 				["markdown"] = cfg,
-- 			},
-- 		})
-- 	end,
-- },
-- {
-- 	"andythigpen/nvim-coverage", -- https://github.com/andythigpen/nvim-coverage
-- 	config = function()
-- 		require("coverage").setup()
-- 	end,
-- },
